## Vision Based Cyclist Travel Lane and Helmet Detection

### Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import cv2

In [ ]:
import os
import csv
import pickle
from sklearn.mixture import GaussianMixture

In [ ]:
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.metrics import confusion_matrix          # to get confusion matrix for testing data
from datetime import datetime                         # to calculate time
from sklearn import linear_model  

## Cyclist Travel Lane

### Importing Data

In [ ]:
folder1 = r"C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane"
folder2 = r"C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane"

In [ ]:
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\cyclist_data.csv', mode='a', header=False,index=False)

In [ ]:
data1 = pd.read_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\cyclist_data.csv',header=None,dtype='uint8')
data1=data1.astype(np.uint8) 
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0       117   15    0    2    3    3    5  129   68  129  ...    0   44    0   
1         1    0    0    0   75  113   16    7   71    0  ...   38  113   40   
2         0    1    0    0    1    4    1    0    0   47  ...    3    7    5   
3        10   62   20   43  102  119   33    0    9  118  ...   65   86   35   
4         0    0    9   18    6    0    0    0    8    0  ...    0    0    3   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
481003   21    2    1    6   11   18   12   20   51    4  ...    0    0    6   
481004   13   10    2    8   20    2    0    1   21    5  ...    0    0    0   
481005    4    0    0  102   36    0    0    2   81    0  ...    0    0   25   
481006   23   10    7   24   10    0    0    2   61    3  ...    4   13   41   
481007   12   24    7   10    6    5    1    1  153   64  ...    0    3    5   

        121  122  123  124  125  126  127  
0         0    0    0    0    0    0    0  
1         0    0    0    0    0    5   86  
2        32   61  100   15    0    0    0  
3         5    0    0   46  119  103   32  
4        84   83    0    0    0    0    1  
...     ...  ...  ...  ...  ...  ...  ...  
481003    0    0    0   25    4    0    0  
481004    0    0    0    0    0    0    0  
481005  133  134   35    1    1    1    0  
481006  142   85   11    1    1    1   10  
481007   29   52   20    2    1    1    2  

[481008 rows x 128 columns]

In [ ]:
i=0
for filename in os.listdir(folder2):
    #path
    path=os.path.join(folder2,filename)
    b=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    print(path)
    img=cv2.resize(b,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\normal_data.csv', mode='a', header=False,index=False)

C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\0.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\10.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\100.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1000.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1001.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1002.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1003.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1004.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1005.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1006.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1007.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVC

In [ ]:
data2= pd.read_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\normal_data.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    0    0    0   15   57    4    0   82   11  ...    0    0    0   
1        21    4    0    0    2   31   12   15  172   10  ...    0    0    4   
2         5   14    9    4    4    1    0    0    6    2  ...    0   19   12   
3         0    8   45  123   51    0    0    0   32  126  ...    5   16    0   
4        20    2    0    0    0    0    0    0   27    0  ...    0    0    0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
628322    1    0    0    1    8    6    1    5   37    0  ...    9   15   78   
628323    6    3    1   10   27   15    4    3   22    1  ...    0    4    0   
628324   22    8    9    4    1    6    2    2  143   27  ...    5   44   70   
628325    0    0    0    0    0    0    0    0    2    0  ...   34   38    1   
628326   16   19   14   21    5    2    1    3   18    4  ...    5   18    0   

        121  122  123  124  125  126  127  
0         1    6    9    1    0    0    0  
1         0    0    1    0    0    0    1  
2         0    0    3  165   62    0    1  
3         0    0    0   26   11    2    0  
4         0    0    7    3    0    0    0  
...     ...  ...  ...  ...  ...  ...  ...  
628322   28    6    4    4    0    1   25  
628323    0    0    0    0    0    0    0  
628324   52    6    1    0    0    9   82  
628325    1    2   11   26   70   25   18  
628326    0    0    0    0    0    0    0  

[628327 rows x 128 columns]

In [ ]:
data=data1.append(data2)

In [ ]:
csv_data=data.to_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\data.csv', mode='a', header=False,index=False)

In [ ]:
data

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0       117   15    0    2    3    3    5  129   68  129  ...    0   44    0   
1         1    0    0    0   75  113   16    7   71    0  ...   38  113   40   
2         0    1    0    0    1    4    1    0    0   47  ...    3    7    5   
3        10   62   20   43  102  119   33    0    9  118  ...   65   86   35   
4         0    0    9   18    6    0    0    0    8    0  ...    0    0    3   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
628322    1    0    0    1    8    6    1    5   37    0  ...    9   15   78   
628323    6    3    1   10   27   15    4    3   22    1  ...    0    4    0   
628324   22    8    9    4    1    6    2    2  143   27  ...    5   44   70   
628325    0    0    0    0    0    0    0    0    2    0  ...   34   38    1   
628326   16   19   14   21    5    2    1    3   18    4  ...    5   18    0   

        121  122  123  124  125  126  127  
0         0    0    0    0    0    0    0  
1         0    0    0    0    0    5   86  
2        32   61  100   15    0    0    0  
3         5    0    0   46  119  103   32  
4        84   83    0    0    0    0    1  
...     ...  ...  ...  ...  ...  ...  ...  
628322   28    6    4    4    0    1   25  
628323    0    0    0    0    0    0    0  
628324   52    6    1    0    0    9   82  
628325    1    2   11   26   70   25   18  
628326    0    0    0    0    0    0    0  

[1109335 rows x 128 columns]

### Data load

In [ ]:
data = pd.read_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\data.csv')

In [ ]:
data

117  15   0   2    3  3.1   5  129   68  129.1  ...  0.36   44  0.37  \
0          1   0   0   0   75  113  16    7   71      0  ...    38  113    40   
1          0   1   0   0    1    4   1    0    0     47  ...     3    7     5   
2         10  62  20  43  102  119  33    0    9    118  ...    65   86    35   
3          0   0   9  18    6    0   0    0    8      0  ...     0    0     3   
4         50  36   2   0    0    0   0    4   33     24  ...   119  134     7   
...      ...  ..  ..  ..  ...  ...  ..  ...  ...    ...  ...   ...  ...   ...   
1109329    1   0   0   1    8    6   1    5   37      0  ...     9   15    78   
1109330    6   3   1  10   27   15   4    3   22      1  ...     0    4     0   
1109331   22   8   9   4    1    6   2    2  143     27  ...     5   44    70   
1109332    0   0   0   0    0    0   0    0    2      0  ...    34   38     1   
1109333   16  19  14  21    5    2   1    3   18      4  ...     5   18     0   

         0.38  0.39  0.40  0.41  0.42  0.43  0.44  
0           0     0     0     0     0     5    86  
1          32    61   100    15     0     0     0  
2           5     0     0    46   119   103    32  
3          84    83     0     0     0     0     1  
4           0     0     0     0     0    33   130  
...       ...   ...   ...   ...   ...   ...   ...  
1109329    28     6     4     4     0     1    25  
1109330     0     0     0     0     0     0     0  
1109331    52     6     1     0     0     9    82  
1109332     1     2    11    26    70    25    18  
1109333     0     0     0     0     0     0     0  

[1109334 rows x 128 columns]

## GMM/KMeans

In [ ]:
import sklearn.cluster as cluster
import seaborn as sns 

In [ ]:
import sklearn.metrics as metrics
for i in range(2,15):
    labels=cluster.KMeans(n_clusters=i,init="k-means++",random_state=200).fit(data).labels_
    print ("Silhouette score for k(clusters) = "+str(i)+" is " +str(metrics.silhouette_score(data,labels,metric="euclidean",sample_size=1000,random_state=200)))

Silhouette score for k(clusters) = 2 is 0.08058356059453035
Silhouette score for k(clusters) = 3 is 0.05955918924775768
Silhouette score for k(clusters) = 4 is 0.0534339813849444
Silhouette score for k(clusters) = 5 is 0.04811133437559269
Silhouette score for k(clusters) = 6 is 0.04475614676159109
Silhouette score for k(clusters) = 7 is 0.047902866303660745
Silhouette score for k(clusters) = 8 is 0.04872878681676818
Silhouette score for k(clusters) = 9 is 0.0506106558470521
Silhouette score for k(clusters) = 10 is 0.048051452420801534
Silhouette score for k(clusters) = 11 is 0.048516837485882834
Silhouette score for k(clusters) = 12 is 0.050382899662799054
Silhouette score for k(clusters) = 13 is 0.04954901569206997
Silhouette score for k(clusters) = 14 is 0.048438037399099174


In [ ]:
kmeans = KMeans(n_clusters=9)
kmeans.fit(data)

KMeans(n_clusters=9)

In [ ]:
# save the model to disk
filename = 'Kmeans_lane_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [ ]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5,6,7,8,9])
print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([ 92372, 135899, 121138, 142322,  87126, 148107, 136062, 137750,
       108558], dtype=int64), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])) 



In [ ]:
i=0
data=[]
k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    print(path)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    #hist= np.histogram(a,bins=[0,1,2,3,4,5,6,7,8])
    hist= np.histogram(a,bins=[0,1,2,3,4,5,6,7,8,9])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\Finalcyclist.csv', mode='a',header=False,index=False)

C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\0.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\10.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\100.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1000.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1001.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1002.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1003.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1004.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1005.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1006.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\cyclist_lane\1007.jpg
C:\Users\CEPlus\Desktop\TYSEM2\Comput

In [ ]:
#performing kmeans prediction of the entire normal_lane dataset with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    resize=(200,200)
    print(path)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7,8,9])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\Finalnormal.csv', mode='a',header=False,index=False)

C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\0.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\10.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\100.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1000.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1001.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1002.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1003.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1004.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1005.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1006.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\normal_lane\1007.jpg
C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVC

In [ ]:
dat1= pd.read_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\Finalcyclist.csv',header=None)
print(dat1)

       0   1   2   3   4   5   6   7   8  9
0     38  80  56  87  38  81  62  44  41  0
1      2  27  32  29  23  18  27   1   1  0
2     39  21   8  26   8  29  30  87  29  0
3     24  43  33  53  22  42  51  39  24  0
4     15  28  40  30  57  15  36  24  32  0
...   ..  ..  ..  ..  ..  ..  ..  ..  .. ..
2995  17  77  60  86  42  97  89  65  28  0
2996  37  40  24  38  16  47  34  48  41  0
2997  16  31  32  31  34  39  42   9  23  0
2998  46  40  23  47  21  48  32  71  42  0
2999  19  23  31  28  10  25  27  37  37  0

[3000 rows x 10 columns]


In [ ]:
dat2= pd.read_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\Finalnormal.csv',header=None)
print(dat2)

       0    1   2    3   4    5    6   7   8  9
0     19   17  11   17  18   10   11  29  25  1
1     19   43  68   50  62   34   40  31  19  1
2     25   60  45   64  17   51   59  55  34  1
3     31   44  40   54  34   54   53  46  28  1
4     10  129  39  122  24   69  103  18  24  1
...   ..  ...  ..  ...  ..  ...  ...  ..  .. ..
1495  23   65  39   72  21   73   75  89  27  1
1496  15  103  78  114  43  117  101  32  31  1
1497  25  103  67  111  75  115   91  54  39  1
1498  39   22  34   30  22   27   21  18  42  1
1499  38   62  10   71   2   70   39  34  58  1

[1500 rows x 10 columns]


In [ ]:
A=dat1.append(dat2)
csv_data=A.to_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\classifier1.csv', mode='a',header=False,index=False)

In [ ]:
A

0    1   2    3   4    5    6   7   8  9
0     38   80  56   87  38   81   62  44  41  0
1      2   27  32   29  23   18   27   1   1  0
2     39   21   8   26   8   29   30  87  29  0
3     24   43  33   53  22   42   51  39  24  0
4     15   28  40   30  57   15   36  24  32  0
...   ..  ...  ..  ...  ..  ...  ...  ..  .. ..
1495  23   65  39   72  21   73   75  89  27  1
1496  15  103  78  114  43  117  101  32  31  1
1497  25  103  67  111  75  115   91  54  39  1
1498  39   22  34   30  22   27   21  18  42  1
1499  38   62  10   71   2   70   39  34  58  1

[4500 rows x 10 columns]

In [ ]:
x = A.iloc[:,0:9].values
x

array([[ 38,  80,  56, ...,  62,  44,  41],
       [  2,  27,  32, ...,  27,   1,   1],
       [ 39,  21,   8, ...,  30,  87,  29],
       ...,
       [ 25, 103,  67, ...,  91,  54,  39],
       [ 39,  22,  34, ...,  21,  18,  42],
       [ 38,  62,  10, ...,  39,  34,  58]], dtype=int64)

In [ ]:
y = A.iloc[:,9].values
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [ ]:
from sklearn.preprocessing import StandardScaler
xs = StandardScaler()
x_pca = xs.fit_transform(x)
x_pca

array([[ 0.32457508,  1.2990115 ,  0.68773061, ...,  0.60937722,
        -0.03242298,  0.26374396],
       [-1.42713773, -0.54464901, -0.22259033, ..., -0.50268943,
        -1.78147439, -1.60427812],
       [ 0.37323377, -0.75336529, -1.13291126, ..., -0.40736943,
         1.71662842, -0.29666266],
       ...,
       [-0.30798788,  2.09909059,  1.10496104, ...,  1.53080388,
         0.37433316,  0.17034286],
       [ 0.37323377, -0.71857925, -0.14673025, ..., -0.69332943,
        -1.08998895,  0.31044451],
       [ 0.32457508,  0.67286265, -1.05705119, ..., -0.12140944,
        -0.43917913,  1.05765334]])

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=None)
pca.fit(x_pca)

PCA()

In [ ]:
cycle_pca = pca.transform(x_pca)
cycle_pca

array([[ 2.28981221, -0.33533002, -0.35145778, ...,  0.52712901,
        -0.23304884,  0.16032685],
       [-2.0323653 , -2.10536409,  0.14544929, ...,  0.1404226 ,
         0.21782453, -0.0576313 ],
       [-1.3631237 ,  1.15366399, -0.43767341, ..., -0.25685122,
         0.09714567,  0.04444375],
       ...,
       [ 4.30800988, -1.40008056,  0.24768306, ...,  0.07279976,
        -0.756037  ,  0.13914988],
       [-1.18855719,  0.45892961,  0.17355197, ...,  0.15271415,
         0.09826987,  0.20984831],
       [ 0.4696181 ,  0.60632551, -1.79837949, ...,  0.64823802,
        -0.43949144,  0.34003259]])

In [ ]:
cycle_pca = pd.DataFrame(cycle_pca)
cycle_pca

0         1         2         3         4         5         6  \
0     2.289812 -0.335330 -0.351458 -0.186397 -0.233036  0.007763  0.527129   
1    -2.032365 -2.105364  0.145449 -0.875723 -0.246276 -0.163950  0.140423   
2    -1.363124  1.153664 -0.437673  1.742377 -0.115683  0.238025 -0.256851   
3    -0.193127 -0.646634 -0.380501  0.055102 -0.169847  0.065735 -0.012093   
4    -0.816590 -0.825566  1.412226 -0.760710  0.120662  0.661091 -0.242729   
...        ...       ...       ...       ...       ...       ...       ...   
4495  1.512799 -0.368624 -0.753107  1.926212  0.014944 -0.020616 -0.219495   
4496  3.978627 -2.157837 -0.765011 -0.327345 -0.063428 -0.420983  0.170448   
4497  4.308010 -1.400081  0.247683  0.187455 -0.285959  0.625390  0.072800   
4498 -1.188557  0.458930  0.173552 -1.167556  0.040582 -0.097253  0.152714   
4499  0.469618  0.606326 -1.798379 -0.490143  0.716025  0.435533  0.648238   

             7         8  
0    -0.233049  0.160327  
1     0.217825 -0.057631  
2     0.097146  0.044444  
3     0.271474  0.059923  
4     0.285960 -0.161650  
...        ...       ...  
4495  0.106381 -0.014102  
4496 -0.259858  0.160878  
4497 -0.756037  0.139150  
4498  0.098270  0.209848  
4499 -0.439491  0.340033  

[4500 rows x 9 columns]

In [ ]:
cycle_pca.shape

(4500, 9)

In [ ]:
print(pca.explained_variance_ratio_) 

[0.54337138 0.1654753  0.11635308 0.09364912 0.03116482 0.02088687
 0.01335868 0.01149743 0.00424333]


In [ ]:
pca = PCA(n_components=6)
pca.fit(x_pca)

PCA(n_components=6)

In [ ]:
# save the model to disk
filename = 'PCA_cycle_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [ ]:
cycle_pca = pca.transform(x_pca)
cycle_pca

array([[ 2.28981221, -0.33533002, -0.35145778, -0.18639663, -0.23303631,
         0.00776349],
       [-2.0323653 , -2.10536409,  0.14544929, -0.87572256, -0.24627578,
        -0.16394971],
       [-1.3631237 ,  1.15366399, -0.43767341,  1.7423771 , -0.11568266,
         0.23802487],
       ...,
       [ 4.30800988, -1.40008056,  0.24768306,  0.18745507, -0.2859586 ,
         0.62539038],
       [-1.18855719,  0.45892961,  0.17355197, -1.16755567,  0.04058207,
        -0.09725311],
       [ 0.4696181 ,  0.60632551, -1.79837949, -0.49014345,  0.71602486,
         0.43553323]])

In [ ]:
cycle_pca.shape

(4500, 6)

In [ ]:
print(pca.explained_variance_ratio_) 

[0.54337138 0.1654753  0.11635308 0.09364912 0.03116482 0.02088687]


In [ ]:
cycle_pca = pd.DataFrame(cycle_pca)
cycle_pca

0         1         2         3         4         5
0     2.289812 -0.335330 -0.351458 -0.186397 -0.233036  0.007763
1    -2.032365 -2.105364  0.145449 -0.875723 -0.246276 -0.163950
2    -1.363124  1.153664 -0.437673  1.742377 -0.115683  0.238025
3    -0.193127 -0.646634 -0.380501  0.055102 -0.169847  0.065735
4    -0.816590 -0.825566  1.412226 -0.760710  0.120662  0.661091
...        ...       ...       ...       ...       ...       ...
4495  1.512799 -0.368624 -0.753107  1.926212  0.014944 -0.020616
4496  3.978627 -2.157837 -0.765011 -0.327345 -0.063428 -0.420983
4497  4.308010 -1.400081  0.247683  0.187455 -0.285959  0.625390
4498 -1.188557  0.458930  0.173552 -1.167556  0.040582 -0.097253
4499  0.469618  0.606326 -1.798379 -0.490143  0.716025  0.435533

[4500 rows x 6 columns]

In [ ]:
B=pd.concat([cycle_pca, pd.DataFrame(y)],axis=1)
B

0         1         2         3         4         5  0
0     2.289812 -0.335330 -0.351458 -0.186397 -0.233036  0.007763  0
1    -2.032365 -2.105364  0.145449 -0.875723 -0.246276 -0.163950  0
2    -1.363124  1.153664 -0.437673  1.742377 -0.115683  0.238025  0
3    -0.193127 -0.646634 -0.380501  0.055102 -0.169847  0.065735  0
4    -0.816590 -0.825566  1.412226 -0.760710  0.120662  0.661091  0
...        ...       ...       ...       ...       ...       ... ..
4495  1.512799 -0.368624 -0.753107  1.926212  0.014944 -0.020616  1
4496  3.978627 -2.157837 -0.765011 -0.327345 -0.063428 -0.420983  1
4497  4.308010 -1.400081  0.247683  0.187455 -0.285959  0.625390  1
4498 -1.188557  0.458930  0.173552 -1.167556  0.040582 -0.097253  1
4499  0.469618  0.606326 -1.798379 -0.490143  0.716025  0.435533  1

[4500 rows x 7 columns]

In [ ]:
csv_data=B.to_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\FinalPCAClassifier1.csv', mode='a',header=False,index=False)

## Training ,Testing & Classification

In [ ]:
data= pd.read_csv(r'C:\Users\CEPlus\Desktop\TYSEM2\ComputerVision\CVCP_dataset\1_classifier_lane\FinalPCAClassifier1.csv',header=None)
data

0         1         2         3         4         5  6
0     2.289812 -0.335330 -0.351458 -0.186397 -0.233036  0.007763  0
1    -2.032365 -2.105364  0.145449 -0.875723 -0.246276 -0.163950  0
2    -1.363124  1.153664 -0.437673  1.742377 -0.115683  0.238025  0
3    -0.193127 -0.646634 -0.380501  0.055102 -0.169847  0.065735  0
4    -0.816590 -0.825566  1.412226 -0.760710  0.120662  0.661091  0
...        ...       ...       ...       ...       ...       ... ..
4495  1.512799 -0.368624 -0.753107  1.926212  0.014944 -0.020616  1
4496  3.978627 -2.157837 -0.765011 -0.327345 -0.063428 -0.420983  1
4497  4.308010 -1.400081  0.247683  0.187455 -0.285959  0.625390  1
4498 -1.188557  0.458930  0.173552 -1.167556  0.040582 -0.097253  1
4499  0.469618  0.606326 -1.798379 -0.490143  0.716025  0.435533  1

[4500 rows x 7 columns]

In [ ]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:6].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,6]
print("Y values")
print(y)

X values
[[ 2.28981221 -0.33533002 -0.35145778 -0.18639663 -0.23303631  0.00776349]
 [-2.0323653  -2.10536409  0.14544929 -0.87572256 -0.24627578 -0.16394971]
 [-1.3631237   1.15366399 -0.43767341  1.7423771  -0.11568266  0.23802487]
 ...
 [ 4.30800988 -1.40008056  0.24768306  0.18745507 -0.2859586   0.62539038]
 [-1.18855719  0.45892961  0.17355197 -1.16755567  0.04058207 -0.09725311]
 [ 0.4696181   0.60632551 -1.79837949 -0.49014345  0.71602486  0.43553323]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
4495    1
4496    1
4497    1
4498    1
4499    1
Name: 6, Length: 4500, dtype: int64


In [ ]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

## Decision tree

In [ ]:
from sklearn.preprocessing import StandardScaler
test1S = StandardScaler()
test1 = test1S.fit_transform(Output)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
#Decision Tree Classifier
#Assign model with Decision Tree classifier
train_start_time = datetime.now()
print('training the model..')
model1 = DecisionTreeClassifier(max_depth=15)
model1.fit(x_train, y_train)
TRAIN_ACCURACY= accuracy_score(y_train, model1.predict(x_train))
print('Done')
train_end_time = datetime.now()
TIMING =  train_end_time - train_start_time
print('training_time(HH:MM:SS.ms) - {}\n\n'.format(TIMING))
#predicting the traget variable using testing variables
test_start_time = datetime.now()
# predict test data
print('Predicting test data')
y_pred1 = model1.predict(x_test)
TESTING_ACCURACY = accuracy_score(y_test, y_pred1)
test_end_time = datetime.now()
TEST_TIMING = test_end_time - test_start_time
print('testing time(HH:MM:SS:ms) - {}\n\n'.format(TEST_TIMING))
#Results
print("Decision Tree Results")
print("Decision Tree Training Accuracy: ",TRAIN_ACCURACY*100,"%")
print("Decision Tree Testing Accuracy: ",TESTING_ACCURACY*100,"%")

print('\n')
print('| Confusion Matrix |')
print('\n')
print(confusion_matrix(y_test, y_pred1))

print('\n')
print(' Classifiction Report ')
print('\n')
classification_report = metrics.classification_report(y_test, y_pred1)
print(classification_report)

training the model..
Done
training_time(HH:MM:SS.ms) - 0:00:00.033910


Predicting test data
testing time(HH:MM:SS:ms) - 0:00:00.002985


Decision Tree Results
Decision Tree Training Accuracy:  97.25 %
Decision Tree Testing Accuracy:  83.22222222222221 %


| Confusion Matrix |


[[568  41]
 [110 181]]


 Classifiction Report 


              precision    recall  f1-score   support

           0       0.84      0.93      0.88       609
           1       0.82      0.62      0.71       291

    accuracy                           0.83       900
   macro avg       0.83      0.78      0.79       900
weighted avg       0.83      0.83      0.83       900



## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
train_start_time = datetime.now()
print('training the model..')
model1 = RandomForestClassifier(n_estimators=100)
model1.fit(x_train, y_train)
TRAIN_ACCURACY= accuracy_score(y_train, model1.predict(x_train))
print('Done')
train_end_time = datetime.now()
TIMING =  train_end_time - train_start_time
print('training_time(HH:MM:SS.ms) - {}\n\n'.format(TIMING))
#predicting the traget variable using testing variables
test_start_time = datetime.now()
# predict test data
print('Predicting test data')
y_pred1 = model1.predict(x_test)
TESTING_ACCURACY = accuracy_score(y_test, y_pred1)
test_end_time = datetime.now()
TEST_TIMING = test_end_time - test_start_time
print('testing time(HH:MM:SS:ms) - {}\n\n'.format(TEST_TIMING))
#Results
print("Random forest Results")
print("Random forest Training Accuracy: ",TRAIN_ACCURACY*100,"%")
print("Random forest Testing Accuracy: ",TESTING_ACCURACY*100,"%")

print('\n')
print('| Confusion Matrix |')
print('\n')
print(confusion_matrix(y_test, y_pred1))

print('\n')
print(' Classifiction Report ')
print('\n')
classification_report = metrics.classification_report(y_test, y_pred1)
print(classification_report)

training the model..
Done
training_time(HH:MM:SS.ms) - 0:00:00.760008


Predicting test data
testing time(HH:MM:SS:ms) - 0:00:00.024313


Random forest Results
Random forest Training Accuracy:  99.91666666666667 %
Random forest Testing Accuracy:  85.44444444444444 %


| Confusion Matrix |


[[591  18]
 [113 178]]


 Classifiction Report 


              precision    recall  f1-score   support

           0       0.84      0.97      0.90       609
           1       0.91      0.61      0.73       291

    accuracy                           0.85       900
   macro avg       0.87      0.79      0.82       900
weighted avg       0.86      0.85      0.85       900



## KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
train_start_time = datetime.now()
print('training the model..')
log_knn = KNeighborsClassifier(n_neighbors=10)
log_knn.fit(x_train, y_train)
TRAIN_ACCURACY= accuracy_score(y_train, log_knn.predict(x_train))
print('Done')
train_end_time = datetime.now()
TIMING =  train_end_time - train_start_time
print('training_time(HH:MM:SS.ms) - {}\n\n'.format(TIMING))

test_start_time = datetime.now()
# predict test data
print('Predicting test data')
y_pred1 = log_knn.predict(x_test)
TESTING_ACCURACY = log_knn.score(x_test,y_test)
test_end_time = datetime.now()
TEST_TIMING = test_end_time - test_start_time
print('testing time(HH:MM:SS:ms) - {}\n\n'.format(TEST_TIMING))


print("KNN Results")
print("KNN Training Accuracy: ",TRAIN_ACCURACY*100,"%")
accuracy = log_knn.score(x_test,y_test)
print("KNN Testing Accuracy: ",TESTING_ACCURACY*100,"%")

print('\n')
print('| Confusion Matrix |')
print('\n')
print(confusion_matrix(y_test, y_pred1))

print('\n')
print(' Classifiction Report ')
print('\n')
classification_report = metrics.classification_report(y_test, y_pred1)
print(classification_report)

training the model..
Done
training_time(HH:MM:SS.ms) - 0:00:00.188459


Predicting test data
testing time(HH:MM:SS:ms) - 0:00:00.093746


KNN Results
KNN Training Accuracy:  76.08333333333334 %
KNN Testing Accuracy:  73.0 %


| Confusion Matrix |


[[536  73]
 [170 121]]


 Classifiction Report 


              precision    recall  f1-score   support

           0       0.76      0.88      0.82       609
           1       0.62      0.42      0.50       291

    accuracy                           0.73       900
   macro avg       0.69      0.65      0.66       900
weighted avg       0.72      0.73      0.71       900

